-- =========================================================
-- VulnCheck & Approve - Alias logiciels connus
-- Formes normalisées (minuscules, underscores) -> couple CPE
-- (vendor, product) tel qu'il apparaît dans les dictionnaires
-- CPE 2.3 du NVD. Extensible par l'équipe Cyber via SQL.
-- =========================================================

INSERT INTO software_aliases (alias, vendor, product) VALUES
    ('anydesk',              'anydesk',        'anydesk'),
    ('chrome',               'google',         'chrome'),
    ('google_chrome',        'google',         'chrome'),
    ('firefox',              'mozilla',        'firefox'),
    ('mozilla_firefox',      'mozilla',        'firefox'),
    ('edge',                 'microsoft',      'edge'),
    ('microsoft_edge',       'microsoft',      'edge'),
    ('vscode',               'microsoft',      'visual_studio_code'),
    ('vs_code',              'microsoft',      'visual_studio_code'),
    ('visual_studio_code',   'microsoft',      'visual_studio_code'),
    ('word',                 'microsoft',      'word'),
    ('excel',                'microsoft',      'excel'),
    ('outlook',              'microsoft',      'outlook'),
    ('teams',                'microsoft',      'teams'),
    ('7zip',                 '7-zip',          '7-zip'),
    ('7_zip',                '7-zip',          '7-zip'),
    ('sevenzip',             '7-zip',          '7-zip'),
    ('winrar',               'rarlab',         'winrar'),
    ('notepad++',            'notepad-plus-plus', 'notepad\+\+'),
    ('notepad_plus_plus',    'notepad-plus-plus', 'notepad\+\+'),
    ('putty',                'putty',          'putty'),
    ('filezilla',            'filezilla-project', 'filezilla_client'),
    ('vlc',                  'videolan',       'vlc_media_player'),
    ('vlc_media_player',     'videolan',       'vlc_media_player'),
    ('teamviewer',           'teamviewer',     'teamviewer'),
    ('zoom',                 'zoom',           'zoom'),
    ('slack',                'slack',          'slack'),
    ('docker',               'docker',         'docker'),
    ('docker_desktop',       'docker',         'desktop'),
    ('openssl',              'openssl',        'openssl'),
    ('openssh',              'openbsd',        'openssh'),
    ('nginx',                'f5',             'nginx'),
    ('apache',               'apache',         'http_server'),
    ('apache_http_server',   'apache',         'http_server'),
    ('tomcat',               'apache',         'tomcat'),
    ('log4j',                'apache',         'log4j'),
    ('postgres',             'postgresql',     'postgresql'),
    ('postgresql',           'postgresql',     'postgresql'),
    ('mysql',                'oracle',         'mysql'),
    ('java',                 'oracle',         'jdk'),
    ('jdk',                  'oracle',         'jdk'),
    ('jre',                  'oracle',         'jre'),
    ('python',               'python',         'python'),
    ('node',                 'nodejs',         'node.js'),
    ('nodejs',               'nodejs',         'node.js'),
    ('node.js',              'nodejs',         'node.js'),
    ('git',                  'git-scm',        'git'),
    ('curl',                 'haxx',           'curl'),
    ('wireshark',            'wireshark',      'wireshark'),
    ('keepass',              'keepass',        'keepass'),
    ('adobe_reader',         'adobe',          'acrobat_reader'),
    ('acrobat_reader',       'adobe',          'acrobat_reader'),
    ('acrobat',              'adobe',          'acrobat')
ON CONFLICT (alias) DO NOTHING;
